#! /usr/bin/env ash
readonly APPLET="${0##*/}"

## Both callmonitor and phonebook are configured via variables in
## $CALLMONITOR_CFG.

. "${CALLMONITOR_CFG:=/etc/default.callmonitor/system.cfg}"
. "$CALLMONITOR_LIBDIR/config.sh"
. "$CALLMONITOR_LIBDIR/applets/$APPLET.sh"
