#! /usr/bin/env ash
##
## Callmonitor for Fritz!Box (callmonitor)
## 
## Copyright (C) 2005--2008  Andreas Bühmann <buehmann@users.berlios.de>
## 
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
## 
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## 
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
## 
## http://developer.berlios.de/projects/callmonitor/
##

## put default names for each SIP account into the phone book
## and print a mapping SIP[0-9] -> SIP address
sip_info() {
    cfg2sh voip |
    sed -ne '
	/^voipcfg_ua[[:digit:]]\+_\(username\|registrar\)=/ {
	    s/^voipcfg_ua\([[:digit:]]\+\)\(.*\)$/\1 \2/
	    p
	}
    ' | {
	SIP_LIST=
	while read num rest; do
	    account="SIP$(($num-1))"
	    case " $SIP_LIST " in
		*" $account "*) ;;
		*) SIP_LIST=$SIP_LIST${SIP_LIST:+ }$account ;;
	    esac
	    echo "$account$rest"
	done
	echo "SIP_LIST=\"$SIP_LIST\""
    }
}

shorten_registrar() {
    local registrar=$1
    local short=$registrar
    short=${short%.*}
    short=${short%.??}
    short=${short##*.}
    echo "$short"
}

add_phonebook_default() {
    local address=$1 name=$2
    if ! phonebook --local exists "$address"; then
	phonebook --persistent put "$address" "$name"
    fi
}

eval "$(sip_info)"

echo "Generating short names for all SIP accounts ..." >&2
for sip in $SIP_LIST; do
    eval 'username=$'$sip'_username'
    eval 'registrar=$'$sip'_registrar'
    address=$username@$registrar
    short=$(shorten_registrar "$registrar")

    echo "$sip: $address -> $short" >&2
    add_phonebook_default "$address" "$short" > /dev/null 2>&1
    echo "${sip}_address=\"$address\""
done
echo "done." >&2
