#!/bin/sh
_usage() {
	cat << EOF
Usage: telfifo {enable|disable} FIFO
       telfifo list
EOF
}

. "${TELEFON_CFG:=/mod/etc/default.telefon/system.cfg}"

if [ ! -d "$TELEFON_FIFODIR" ]; then
	mkdir -p "$TELEFON_FIFODIR"
fi

_enable() {
	local FIFO="$1"
	if [ -d "$FIFO" ]; then
		echo "$FIFO is a directory" >&2
		exit 1
	fi
	if [ ! -w "$FIFO" ]; then
		echo "$FIFO is not writable" >&2
		exit 1
	fi
	let id="$(ls -r "$TELEFON_FIFODIR" | head -1) + 1"
	ln -s "$FIFO" "$TELEFON_FIFODIR/$id"
}
_disable() {
	local FIFO="$1"
	real_fifo="$(realpath "$FIFO")"
	for fifo in "$TELEFON_FIFODIR"/*; do
		[ -e "$fifo" ] || continue
		if [ "$real_fifo" = "$(realpath "$fifo")" ]; then
			rm "$fifo"
		fi
	done
}

case "$1" in
	enable|disable)
		if [ $# -lt 2 ]; then
			_usage >&2
			exit 1
		fi
		case "$2" in
			/*) FIFO="$2" ;;
			*)  FIFO="$PWD/$2" ;;
		esac
		;;
esac
case "$1" in
	enable)
		_disable "$FIFO"
		_enable "$FIFO"
		"$TELEFON_RC" reload
		;;
	disable)
		_disable "$FIFO"
		"$TELEFON_RC" reload
		;;
	list)
		ls -lF "$TELEFON_FIFODIR"
		;;
	*)
		_usage >&2
		exit 1
		;;
esac
