#! /bin/sh
ARCHIVE="${1##*/}"
case $ARCHIVE in
    *-*-root.tar) ;;
    *)
	echo "Usage: $0 <package>-<version>-root.tar" >&2
	exit 1
    ;;
esac
PKGVER="${ARCHIVE%-root.tar}"
VER="${PKGVER##*-}"
PKG="${PKGVER%-$VER}"
MOD_ROOT='/var/mod'
if [ ! -d "$MOD_ROOT" ]; then
    mkdir -p "$MOD_ROOT"
fi
tar xf "$ARCHIVE" -C "$MOD_ROOT"
"$MOD_ROOT/etc/init.d/rc.$PKG" load
mkdir -p "$MOD_ROOT/pkg"
ln -s .. "$MOD_ROOT/pkg/$PKG"
