#!/bin/sh
readonly PROGRAM="${0##*/}"
readonly LOG="/var/log/callmonitor.log"
usage() {
	cat <<EOF
Usage:	callmonitor [OPTION]...
Options:
	-f	run in foreground
	-s	stop the callmonitor
	--debug	log rule matching/executed commands to $LOG
		(or to stderr with -f)
	--help	show this help
EOF
}

# Both callmonitor and phonebook are configured via variables in
# $CALLMONITOR_CFG.

. "${CALLMONITOR_CFG:=/mod/etc/default.callmonitor/system.cfg}"

require callmonitor

# parse options
TEMP="$(getopt -o 'fs' -l debug,help -n "$PROGRAM" -- "$@")" || exit 1
eval "set -- $TEMP"

DEBUG=false
FOREGROUND=false
STOP=false
while true; do
	case $1 in
		-f) FOREGROUND=true ;;
		-s) STOP=true ;;
		--debug) DEBUG=true ;;
		--help) usage 1>&2; exit ;;
		--) shift; break ;;
		*) ;; # should never happen
	esac
	shift
done

# pass options to phonebook
PHONEBOOK_OPTIONS=""
if $DEBUG; then
	PHONEBOOK_OPTIONS="$PHONEBOOK_OPTIONS --debug"
fi

# set up logging
__log_setup() {
	if $DEBUG; then
		if ! $FOREGROUND; then
			__debug() { echo "$PROGRAM: $*" >> "$LOG"; }
		else
			__debug() { echo "$PROGRAM: $*" >&2; }
		fi
		__debug "entering DEBUG mode"
	else
		__debug() :
	fi
	if $FOREGROUND; then
		incoming_call() { __incoming_call "$@"; }
	else
		incoming_call() { __incoming_call "$@" > /dev/null 2>&1; }
	fi
}

__work() {
	# a USR1 signal will cause the callmonitor to re-read its configuration
	trap __configure USR1
	trap 'rm -f "$PIDFILE"' EXIT
	trap 'exit 2' HUP INT QUIT TERM

	# initial configuration
	__log_setup
	__configure

	# enter main loop
	while true; do
		__read < "$FIFO"
	done
}

PIDFILE="/var/run/callmonitor.pid"
FIFO="/var/run/callmonitor/fifo"

if $STOP; then
	if [ ! -e "$PIDFILE" ]; then
		echo "$PROGRAM: not running" 2>&1 
		exit 1
	else
		PID="$(cat "$PIDFILE")"
		kill "$PID" && rm -f "$PIDFILE"
		exit $?
	fi
else
	mkdir -p "$(dirname "$FIFO")"

	if [ ! -p "$FIFO" ]; then
		mknod "$FIFO" p
	fi

	if $FOREGROUND; then
		echo $$ > "$PIDFILE"
		__work
	else
		__work &
		echo $! > "$PIDFILE"
	fi
fi
