#! /usr/bin/env ash
readonly APPLET="${0##*/}"

# Both callmonitor and phonebook are configured via variables in
# $CALLMONITOR_CFG.

. "${CALLMONITOR_CFG:=/mod/etc/default.callmonitor/system.cfg}" # FIXME
. "$CALLMONITOR_LIBDIR/applets/$APPLET.sh"
