#! /usr/bin/env ash
readonly APPLET=${0##*/}

## Both callmonitor and phonebook are configured via variables in
## $CALLMONITOR_CFG. This is the only variable to be customized here.

## requires /etc/default.callmonitor/system.cfg
## requires /usr/lib/callmonitor/config.sh
## requires /usr/lib/callmonitor/applets/controller.sh
. "$CALLMONITOR_CFG"
. "$CALLMONITOR_LIBDIR/config.sh"
. "$CALLMONITOR_LIBDIR/applets/$APPLET.sh"
